### ISSUE TITLE
look at grid simulators

### ISSUE THREAD

**Issue by anaderi** [ffloyd/evergrid_rails#10]
перед тем как бросаться на реализацию, можно посмотреть в сторону существующих симуляторов грида - может быть какие-то из них предоставляют нужную функциональность. либо убедиться что ни один из низ нам не годится
1. Job Scheduling Simulator http://www.fi.muni.cz/~xklusac/alea/ с статья по нему http://www.fi.muni.cz/~xklusac/pub/alea2.pdf
2. Симулятор SimGrid http://www.buyya.com/gridsim/ статьи по нему на странице. Например, http://www.buyya.com/gridsim/paper/datagrid_ccpe.pdf и http://www.cloudbus.org/papers/anss41-canada-keynote2008.pdf http://simgrid.gforge.inria.fr/download.php
3. Набор статей по симулятору (SyMSim) грида в ОИЯИ, Дубна:
   http://ceur-ws.org/Vol-1297/13-19_paper-4.pdf
   http://www.mathnet.ru/links/2012ff65a8cbb0cb7ea3a9fab59d37fa/ssi390.pdf
   У них даже свой сайт есть: http://symsim.jinr.ru/project/o-nas-2/

**Comment by ffloyd** [comment]
Разбираюсь тут с написанным в статьях. Вы говорили, что “перед тем как бросаться на реализацию, можно посмотреть в сторону существующих симуляторов грида” в контексте задачи про архитектуру. Но чтобы понять применимость simgrid, alea или осознать необходимость писать свой симулятор надо как раз таки в первую очередь определиться с архитектурой.

**Comment by ffloyd** [comment]
Задача уже неактуальна.
