### ISSUE TITLE
Basic datasets uploading

### ISSUE THREAD

**Issue by ffloyd** [ffloyd/evergrid_rails#4]
Вариант с прямой загрузкой:
- на датацентры повесить агент, который может принимать файл по HTTP и сохранять его
- на web-части запилить форму, с прогрессбаром, отправляющую этот файл на загрузку.
- в идеале: агент начинает принимать файлы только по указанию сервера и наличии одноразовой крипто-куки выставленной на web-части

Если окажется слишком дорого по времени: сделать тривиальную двухэтапную загрузку

**Comment by anaderi** [comment]
двухэтапную?

**Comment by ffloyd** [comment]
@anaderi Сначала загружается на машину с web-воркером, затем оттуда посылается в кластер.

Сейчас еще раз подумав, мне кажется, что для прототипа двухэтапность вполне подойдет. Все же рассылка напрямую в один из компонентов кластера - это относительно тяжелой задачей может оказаться. К тому же, для "прямой" отсылки придется "дописывать", а не переписывать код.

**Comment by anaderi** [comment]
ok

**Comment by ffloyd** [comment]
Задача уже неактуальна.
