### ISSUE TITLE
Choose right architecture

### ISSUE THREAD

**Issue by ffloyd** [ffloyd/evergrid_rails#6]
## Предпосылки

Изначально предполагалось, что машины, предоставляемые пользователем, будут полноценной частью распределенного кластера. Распределенность же будет обеспечиваться некой проверенной временем технологией. Первый кандидат на эту роль - nomad. Так же нам нужно внедрить свой шедулер, чтобы контролировать логику нагрузки и распределения датасетов между машинами.

Размышления по этому поводу привели к мысли, что подобный подход имеет три недостатка.
### Безопасность

Это огромнейший недостаток такой архитектуры. Если процесс управления кластером может происходить на машине пользователя - то значит пользователь может перехватить управление кластером.

Эта проблема имеет решение - криптовалюты вроде bitcoin это, по сути, распределенные вычислительные кластеры. Обход указанного недостатка основан на том, что действие должны подтвердить N случайных участников сети.

Но рассматриваемые нами решения для управления кластерами априори предполагают, что у пользователя нет root-доступа к нодам. А их security best practices основаны на идее максимально усложнить возможность получения подобного доступа путем изоляции сред выполнения и прочих ограничений свобод.

Поскольку задача нетипичная, то решений скорее всего нет или они не настолько хорошо обкатаны как nomad и аналоги.
### Внедрение своего шедулера

Это тоже проблема, пусть и меньших масштабов. Проекты вроде nomad своей целью ставят как раз таки абстрагировать нас от написания своих планировщиков. Их цель - предоставить удобный интерфейс для быстрого закидывания инфраструктурных компонентов.

Конечно, кто-то из них может предоставлять API или открытые исходные коды, но в обоих случаях есть риск борьбы против идеологии заложенной в систему и уж точно придется разбираться с не самым простым интерфейсом. Что, определенно, сомнительная задача в рамках прототипа.
### Невозможность использовать nomad и другие разработки hashicorp

Меньший из трех недостатков. Nomad плохо подходит для поставленной задачи. Но почитав доки consul'а, serf'а и других продуктов hashicorp - я понял, что мне очень нравится их подход. Меня прям проняло - а их последний продукт - otto - это вообще очень интересная концепция.

Hashicorp умеют делать сложные вещи максимально простыми и осознаваемыми. Их подход к архитектуре заслуживает подражания. Среди прочих аналогов продукты этой компании для меня в приоритете.

Из стека docker в таком случае интерес представляют в первую очередь docker, docker-compose и docker-machine
## Решение вышеуказанных проблем

Если переформулировать проблемы в требования к архитектуре, то получим следующий список:
1. машины пользователей не должны иметь доступ к управлению кластером. Никогда.
2. нужна возможность написать свой шедулер с нуля. Точнее только логику распределения нагрузки и датасетов. Мониторинг, проверку доступности, consistency - все это можно решать другими инструментами. Точнее - надо просто написать специфичный load balancer.
3. постараться решить все средствами hashicorp и docker/docker-compose/docker-machine

На основе этих требований я придумал архитектуру, придумал ночью так что это subject to change. Но прийти к соглашению надо быстрее, т. к. от этого выбора зависит то, как и где писать код.

Сначала приведу список компонентов системы, потом особенности их функционирования как единого целого:
- **nginx** - reverse proxy и раздача статики. Тут все просто.
- **web** - веб морда на rails. Минимум кода связанного с управлением загрузками. Также схема БД управляется средствами rails (миграции, инициализация).
- **db** - postgresql база для _web_ и _core_. Все то, что мы хотим показывать пользователю и сохранять результат должно лежать здесь.
- **core** - это JSON API сервис написанный на go, который общается с _web_ и _db_. С _web_ ему поступают запросы - а он уже либо сам их выполняет, либо делегирует сети _agent_'ов. Также, без запроса со стороны _web_ может обновлять данные в _db_.
- **agent** - сердце системы. JSON API сервис написанный на go. load balancer и task executer. Существует во множественном числе образуя кластер. О его работе и взаимодействии с ним ниже.
- **worker** - непосредственно предоставленные пользователями мощности. Общаются только с _agent_'ами. Специального кода не нужно, т. к. управление можно полностью положить на плечи docker-machine.
### Сеть _agent_'ов

Для распределения нагрузки нужна сеть приватных серверов. Их правильно располагать по датацентрам: например по одному на каждый DO-регион. Либо просто по регионам.

На каждом приватном сервере запущен _agent_. А также запущен [consul](https://www.consul.io) - он обеспечивает service discovery и объединяет _agent_'ы в кластер.

Также consul имеет встроенный [механизм для leader election](https://www.consul.io/docs/guides/leader-election.html). Это может быть нужно для того, чтобы _agent_'ы могли выбирать лидера для выполнения определенных задач, где удобен выделенный решатель.

[Механизм для разбиения на датацентры](https://www.consul.io/docs/guides/datacenters.html) полезен для availablity. Без него consul сконцентрирован на consistency и посчитает кластер мертвым если упадут `N/2 + 1` ключевых нод.

Сами _agent_'ы обладают следующими свойствами:
- _worker_ может быть привязан только к одному агенту. Выбор осуществляется на основе лучшего ping'а и других сетевых параметров.
- у каждого есть своя личная очередь задач
- если очередь движется медленно - можно попробовать делегировать задачу другому агенту
- запрос на новую задачу можно посылать любому агенту - он сам ее делегирует в правильное место
- можно спросить кластер на предмет расположения датасета(ов), собранных образов и пр.
- можно попросить предзагрузить датасет или прекомпилировать образ.
- может инициализировать ресурсы пользователя с помощью docker-machine
- если датацентр отрезан от остальной сети - _agent_ просто продолжает выполнять свою очередь общаясь с другими доступными агентами и ждет, пока критические участки снова поднимутся, чтобы отправить результаты.
- можно еще долго продолжать список нужными и не очень фичами - но общая суть, думаю, ясна
### Deployment & configuration

_nginx_, _web_, _db_ и _core_ в рамках прототипа лежат на одной машине. Также на этой машине запущен consul. Эта связка образует отдельный датацентр "web" - так что _agent_'ы могут понять, доступен ли им этот узел или нет.

Приватные сервера содержат только _agent_ и consul.

Деплой как "web" так и _agent_'ов проще всего сделать через docker-compose и docker-machine автоматизировав несколькими bash-скриптами. Для прототипа внедрение orchestration tool может оказаться излишним. Но если будет желание и ресурсы - наиболее интересный кандидат: [terraform](https://www.terraform.io/).
## Заключение

Можно еще написать килобайты текста обо всем этом, но на данный момент задачей является обозначить проблемы и предложить альтернативную архитектуру для их решения. Дальнешие уточнения и обсуждения будут более уместны в комментариях.

**Comment by anaderi** [comment]
перед тем как приступать к реализации, нужно посмотреть на симуляторы грида #10

**Comment by ffloyd** [comment]
@anaderi https://docs.google.com/document/d/1yTs5hWaybtgCVX-sGXUSs0l-kF8pZPRaOp-gEGUsVmE/edit?usp=sharing

Расписал и нарисовал.

**Comment by ffloyd** [comment]
Задача уже неактуальна.
