### ISSUE TITLE
Integrate rollbar

### ISSUE THREAD

**Issue by ffloyd** [ffloyd/evergrid_rails#7]
Есть замечательный проект для отлова ошибок в production: https://rollbar.com/

Перед тем, как задеплоить evergrid на DO имеет смысл подрубить rollbar, чтобы не лезть из-за каждой ошибки в логи.

5000 ошибок в месяц бесплатно. Этого для прототипа более чем хватит.

Есть поддержка как ruby/rails, так и go.

**Comment by anaderi** [comment]
:+1:

**Comment by ffloyd** [comment]
Задача уже неактуальна.
