### ISSUE TITLE
при создании ДЦ, нужно указывать с какими ДЦ он связан и запрашивать веса этих связей

### ISSUE THREAD

**Issue by anaderi** [ffloyd/evergrid_rails#9]
хоть это выглядит немного искусственно, но даст какое-то представление о топологии сети ДЦ
чем больше вес - тем больше пинг

**Comment by ffloyd** [comment]
Не понял о чем идет речь. О добавлении "искусственного" параметра "задержки" для моделирования?

К тому же надо определиться с терминологией. DC есть в контексте consul'а, пользовательские машины сейчас тоже называются DC. После того как определимся с архитектурой надо будет подправить описание задачи.

**Comment by anaderi** [comment]
да, задержка, чтобы моделировать удаленность одних хостов от других.
под ДЦ я имел ввиду кластер, предоставляемый пользователем (например, пачка хостов от Карины)

**Comment by ffloyd** [comment]
Может лучше это сделать на системном уровне? Я так понял, нам нужно будет моделировать различные топологии и неурядицы с коннектом. Поэтому мне кажется правильней организовать тестовую среду. Рассуждать буду в рамках предложенной мной архитектуры в #6 :

Подробнее:
- давай называть ресурс, предоставляемый пользователем - воркером. Также есть агенты, управляющие воркером и ядро, которое инициирует процессы (получая запросы от rails)
- поскольку нам захочется прогонять алгоритм на различных конфигурациях - то каждый раз что-то самому делать через интерфейс - не очень затея.
- поэтому предлагаю сделать для тестирования использовать docker-compose. У агентов и core будет специальный режим, который будет учитывать "искусственную" топологию.
- главная фича воркеров - то, что они могут запускать docker-контейнеры. И это тоже можно симулировать т. к. [можно запускать докер внутри докера](https://blog.docker.com/2013/09/docker-can-now-run-within-docker/)
- причем работу веб-части симулировать не нужно будет - core просто будет слать запросы в кластер по заданному сценарию - для этого ни web, ни db не нужны
- профиты - возможность писать "unit-тесты" на работу алгоритма
- опасности - надеюсь моих SSD, core i7 4hz и 16 gb ram хватит, чтобы это работало и работало достаточно быстро.
- возможное упрощение, которое стоит пытаться сделать: использовать пачку getcarina-нод вместо "искусственных" воркеров

**Comment by ffloyd** [comment]
Задача уже неактуальна.
